pipeline{


agent any


    tools{
        maven 'Maven3'
        jdk 'JDK21'

    }


    stages{
        stage('Checkout scm'){
            
            steps{
             git branch: 'main', url: 'https://github.com/RRitsolution/simplemavenproject.git'
        }

    }
    

    stage('Build maven package & deplot to remote repo'){
        steps{
            sh 'cd my-app && mvn clean deploy'
        }
    }
       
    }
    
    post {
        success {
            echo "Build successful! Artifact is in target/ folder."
        }
        failure {
            echo "Build failed."
        }
    }
}
